// L-0 AOT Compiler - Generates C code from L-0 bytecode
// Uses proxy call interface for TEXEC to support dynamic plugins
//
// 编译: cargo build --release --bin l0cc
// 用法: l0cc program.l0 -o program.c && gcc -O2 program.c -o program

use l0_core::*;
use std::env;
use std::fs;
use std::collections::HashMap;
use serde_json::Value;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("L-0 AOT Compiler");
        eprintln!("Usage: l0cc <program.l0|program.json> [-o output.c]");
        eprintln!("       l0cc --standalone <program> [-o output.c]  # Generate self-contained binary");
        std::process::exit(1);
    }

    let standalone = args.contains(&"--standalone".to_string());
    let input_path = args.iter().skip(1).find(|a| !a.starts_with("-") && *a != "--standalone")
        .expect("No input file specified");

    let output_path = args.iter().position(|a| a == "-o")
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
        .unwrap_or("output.c");

    // Load program
    let program: Vec<Instruction> = if input_path.ends_with(".json") {
        let content = fs::read_to_string(input_path).expect("Failed to read JSON file");
        serde_json::from_str(&content).expect("Failed to parse L-0 JSON program")
    } else {
        let content = fs::read(input_path).expect("Failed to read binary file");
        bincode::deserialize(&content).expect("Failed to parse L-0 Binary Bytecode")
    };

    // Load tools.json for TEXEC mapping
    let tools = load_tools();

    // Generate C code
    let c_code = generate_c_code(&program, &tools, standalone);

    fs::write(output_path, &c_code).expect("Failed to write output file");
    eprintln!("Generated: {} ({} bytes)", output_path, c_code.len());
    eprintln!("Compile with: gcc -O2 {} -o program", output_path);
}

fn load_tools() -> HashMap<u16, (String, String)> {
    let mut tools = HashMap::new();
    let paths = ["tools.json", "env/tools.json"];

    for path in &paths {
        if let Ok(content) = fs::read_to_string(path) {
            if let Ok(json) = serde_json::from_str::<Value>(&content) {
                for section in ["plugins", "builtins"] {
                    if let Some(plugins) = json.get(section) {
                        if let Some(obj) = plugins.as_object() {
                            for (k, v) in obj {
                                let id = if k.starts_with("0x") {
                                    u16::from_str_radix(&k[2..], 16).unwrap_or(0)
                                } else {
                                    k.parse().unwrap_or(0)
                                };
                                let name = v["name"].as_str().unwrap_or("UNKNOWN").to_string();
                                let kind = v["type"].as_str().unwrap_or("builtin").to_string();
                                tools.insert(id, (name, kind));
                            }
                        }
                    }
                }
            }
            break;
        }
    }
    tools
}

fn generate_c_code(program: &[Instruction], tools: &HashMap<u16, (String, String)>, standalone: bool) -> String {
    let mut code = String::new();

    // Header
    code.push_str(r#"/*
 * L-0 AOT Compiled Program
 * Generated by l0cc (L-0 Ahead-of-Time Compiler)
 *
 * Compile: gcc -O2 -o program program.c
 * Run: ./program
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>

// === VM State ===
static int64_t regs[256];
static int flag_eq = 0, flag_gt = 0, flag_lt = 0;

// === Linear Heap (v2.0) ===
#define HEAP_SIZE (16 * 1024 * 1024)  // 16MB

typedef struct {
    size_t offset;
    size_t size;
    int used;
} Allocation;

static unsigned char* heap_buffer = NULL;
static Allocation allocations[65536];
static int64_t next_ptr = 1;
static size_t heap_bump = 0;

static void heap_init(void) {
    if (!heap_buffer) {
        heap_buffer = (unsigned char*)malloc(HEAP_SIZE);
        memset(heap_buffer, 0, HEAP_SIZE);
    }
}

static int64_t heap_alloc(const char* data, size_t len) {
    heap_init();
    if (len == 0) return 0;
    if (heap_bump + len > HEAP_SIZE) return 0;  // OOM

    size_t offset = heap_bump;
    heap_bump += len;

    if (data) memcpy(heap_buffer + offset, data, len);

    int64_t ptr = next_ptr++;
    if (ptr >= 65536) return 0;  // Too many allocations

    allocations[ptr].offset = offset;
    allocations[ptr].size = len;
    allocations[ptr].used = 1;

    return ptr;
}

static int64_t heap_alloc_str(const char* str) {
    return heap_alloc(str, strlen(str) + 1);  // Include null terminator
}

static unsigned char* heap_get(int64_t ptr) {
    if (ptr <= 0 || ptr >= next_ptr || !allocations[ptr].used) return NULL;
    return heap_buffer + allocations[ptr].offset;
}

static size_t heap_len(int64_t ptr) {
    if (ptr <= 0 || ptr >= next_ptr || !allocations[ptr].used) return 0;
    return allocations[ptr].size;
}

static void heap_free(int64_t ptr) {
    if (ptr > 0 && ptr < next_ptr) {
        allocations[ptr].used = 0;
    }
}

"#);

    // TEXEC proxy - key feature for dynamic plugin support
    code.push_str(r#"// === TEXEC Proxy (supports dynamic plugins via tools.json) ===
static char* texec_builtin(int tool_id, const char* arg) {
    static char buf[4096];
    buf[0] = '\0';

    switch (tool_id) {
        case 0x5000: // PRINT
            printf("%s\n", arg);
            break;
        case 0x5001: // PRINTN
            printf("%s", arg);
            fflush(stdout);
            break;
        case 0x5002: // INPUT
            if (fgets(buf, sizeof(buf), stdin)) {
                buf[strcspn(buf, "\n")] = '\0';
            }
            break;
        case 0x5003: // RAND
            snprintf(buf, sizeof(buf), "%ld", (long)(rand() % (atol(arg) ?: 100)));
            break;
        case 0x5004: // STRLEN
            snprintf(buf, sizeof(buf), "%lu", (unsigned long)strlen(arg));
            break;
        case 0x5005: // ABS
            snprintf(buf, sizeof(buf), "%ld", labs(atol(arg)));
            break;
        case 0x5006: // MIN
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2)
                    snprintf(buf, sizeof(buf), "%ld", a < b ? a : b);
            }
            break;
        case 0x5007: // MAX
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2)
                    snprintf(buf, sizeof(buf), "%ld", a > b ? a : b);
            }
            break;
        case 0x5008: // TIME
            snprintf(buf, sizeof(buf), "%ld", (long)time(NULL));
            break;
        case 0x5009: // CONCAT
            {
                const char* comma = strchr(arg, ',');
                if (comma) {
                    int len1 = comma - arg;
                    snprintf(buf, sizeof(buf), "%.*s%s", len1, arg, comma + 1);
                }
            }
            break;
        case 0x500C: // UPPER
            for (int i = 0; arg[i] && i < sizeof(buf)-1; i++)
                buf[i] = (arg[i] >= 'a' && arg[i] <= 'z') ? arg[i] - 32 : arg[i];
            break;
        case 0x500D: // LOWER
            for (int i = 0; arg[i] && i < sizeof(buf)-1; i++)
                buf[i] = (arg[i] >= 'A' && arg[i] <= 'Z') ? arg[i] + 32 : arg[i];
            break;
        case 0x500E: // TRIM
            {
                const char* start = arg;
                while (*start == ' ' || *start == '\t') start++;
                const char* end = arg + strlen(arg) - 1;
                while (end > start && (*end == ' ' || *end == '\t')) end--;
                int len = end - start + 1;
                strncpy(buf, start, len);
                buf[len] = '\0';
            }
            break;
        case 0x1004: // POW
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2) {
                    long result = 1;
                    for (int i = 0; i < b; i++) result *= a;
                    snprintf(buf, sizeof(buf), "%ld", result);
                }
            }
            break;
        default:
            snprintf(buf, sizeof(buf), "[Tool 0x%04X not implemented]", tool_id);
    }
    return buf;
}

// Plugin proxy - calls external plugins via pipe
static char* texec_plugin(int tool_id, const char* arg) {
    static char buf[4096];
    buf[0] = '\0';

    // For standalone mode, plugins are not supported
    // In full mode, this would spawn the plugin process
    snprintf(buf, sizeof(buf), "[Plugin 0x%04X requires runtime]", tool_id);
    return buf;
}

static int texec(int tool_id, int arg_reg, int dest_reg) {
    unsigned char* raw = heap_get(regs[arg_reg]);
    const char* arg = raw ? (const char*)raw : "";
    char* result;

    // Check if builtin (0x5xxx, 0x1xxx) or plugin (others)
    if ((tool_id & 0xF000) == 0x5000 || (tool_id & 0xF000) == 0x1000) {
        result = texec_builtin(tool_id, arg);
    } else {
        result = texec_plugin(tool_id, arg);
    }

    regs[dest_reg] = heap_alloc_str(result);
    return 0;
}

// String helper for safe heap access
static const char* heap_str(int64_t ptr) {
    unsigned char* raw = heap_get(ptr);
    return raw ? (const char*)raw : "";
}

"#);

    // Helper functions
    code.push_str(r#"// === Helper Functions ===
static void itoa_reg(int dest, int src) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%ld", (long)regs[src]);
    regs[dest] = heap_alloc_str(buf);
}

static void atoi_reg(int dest, int src) {
    regs[dest] = atol(heap_str(regs[src]));
}

static void scat_reg(int dest, int s1, int s2) {
    const char* str1 = heap_str(regs[s1]);
    const char* str2 = heap_str(regs[s2]);
    size_t len = strlen(str1) + strlen(str2);
    char* buf = malloc(len + 1);
    strcpy(buf, str1);
    strcat(buf, str2);
    regs[dest] = heap_alloc(buf, len + 1);  // Include null terminator
    free(buf);
}

// Simple regex match using POSIX regex (compile with -lregex on some systems)
#include <regex.h>
static int regex_match(const char* pattern, const char* text) {
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED | REG_NOSUB) != 0) return 0;
    int result = (regexec(&re, text, 0, NULL, 0) == 0) ? 1 : 0;
    regfree(&re);
    return result;
}

// === Supervisor Protocol (Governance) ===
// JSON communication with AI supervisor for drift control
static int trapped = 0;
static int trap_code = 0;
static int current_pc = 0;

// Simple JSON string builder
static void emit_json_kv_str(FILE* out, const char* key, const char* val, int is_last) {
    fprintf(out, "\"%s\":\"%s\"%s", key, val, is_last ? "" : ",");
}
static void emit_json_kv_int(FILE* out, const char* key, int64_t val, int is_last) {
    fprintf(out, "\"%s\":%ld%s", key, (long)val, is_last ? "" : ",");
}

// Emit trap context to stdout for supervisor
static void supervisor_emit_trap(const char* trap_type, int code, int pc) {
    printf("{");
    emit_json_kv_str(stdout, "trap", trap_type, 0);
    emit_json_kv_int(stdout, "code", code, 0);
    emit_json_kv_int(stdout, "pc", pc, 0);
    printf("\"registers_0_15\":[");
    for (int i = 0; i < 16; i++) {
        printf("%ld%s", (long)regs[i], i < 15 ? "," : "");
    }
    printf("],");
    emit_json_kv_int(stdout, "last_similarity", regs[243], 1);
    printf("}\n");
    fflush(stdout);
}

// Emit drift context for GUARD instruction
static void supervisor_emit_drift(int pc, int64_t similarity, int state_reg) {
    printf("{");
    emit_json_kv_str(stdout, "trap", "DRIFT", 0);
    emit_json_kv_int(stdout, "code", 1, 0);
    emit_json_kv_int(stdout, "pc", pc, 0);
    emit_json_kv_int(stdout, "similarity", similarity, 0);
    printf("\"governance\":{");
    emit_json_kv_int(stdout, "R240_target", regs[240], 0);
    emit_json_kv_int(stdout, "R241_state", regs[state_reg], 0);
    emit_json_kv_int(stdout, "R242_threshold", regs[242], 0);
    emit_json_kv_int(stdout, "R243_last_sim", regs[243], 1);
    printf("}}\n");
    fflush(stdout);
}

// Emit YIELD query for supervisor
static void supervisor_emit_yield(const char* query, int query_reg, int pc) {
    printf("{\"yield\":true,\"query\":\"%s\",\"query_reg\":%d,\"pc\":%d}\n",
           query, query_reg, pc);
    fflush(stdout);
}

// Wait for and parse supervisor response
// Returns: 0=continue, 1=abort, 2=jump (new PC in *new_pc)
static int supervisor_wait(int* new_pc) {
    static char buf[8192];
    fprintf(stderr, "[GOVERNANCE] Awaiting supervisor response (JSON)...\n");

    if (!fgets(buf, sizeof(buf), stdin)) {
        return 1; // EOF = abort
    }

    // Minimal JSON parsing for supervisor protocol
    // Expected: {"action":"continue"} or {"action":"abort"} or {"jump":N}
    // Also supports: {"set_registers":{"0":123,"1":456}}

    // Parse action
    char* action_pos = strstr(buf, "\"action\"");
    if (action_pos) {
        if (strstr(action_pos, "\"continue\"")) {
            fprintf(stderr, "[GOVERNANCE] Supervisor: continue\n");

            // Check for set_registers
            char* set_regs = strstr(buf, "\"set_registers\"");
            if (set_regs) {
                // Parse simple {key:val} pairs
                char* brace = strchr(set_regs, '{');
                if (brace) {
                    char* p = brace + 1;
                    while (*p && *p != '}') {
                        while (*p && (*p == ' ' || *p == '"' || *p == ',')) p++;
                        if (*p == '}') break;

                        // Parse register index
                        int reg_idx = 0;
                        while (*p >= '0' && *p <= '9') {
                            reg_idx = reg_idx * 10 + (*p - '0');
                            p++;
                        }

                        // Skip to value
                        while (*p && *p != ':') p++;
                        if (*p == ':') p++;
                        while (*p == ' ') p++;

                        // Parse value (handle negative)
                        int neg = 0;
                        if (*p == '-') { neg = 1; p++; }
                        int64_t val = 0;
                        while (*p >= '0' && *p <= '9') {
                            val = val * 10 + (*p - '0');
                            p++;
                        }
                        if (neg) val = -val;

                        if (reg_idx >= 0 && reg_idx < 256) {
                            regs[reg_idx] = val;
                            fprintf(stderr, "[GOVERNANCE] Set R%d = %ld\n", reg_idx, (long)val);
                        }
                    }
                }
            }
            return 0;
        } else if (strstr(action_pos, "\"abort\"")) {
            fprintf(stderr, "[GOVERNANCE] Supervisor: abort\n");
            return 1;
        }
    }

    // Parse jump
    char* jump_pos = strstr(buf, "\"jump\"");
    if (jump_pos) {
        char* colon = strchr(jump_pos, ':');
        if (colon) {
            *new_pc = atoi(colon + 1);
            fprintf(stderr, "[GOVERNANCE] Supervisor: jump to %d\n", *new_pc);
            return 2;
        }
    }

    // Parse response (for YIELD)
    char* resp_pos = strstr(buf, "\"response\"");
    if (resp_pos) {
        return 0; // Continue with response parsed
    }

    // Default: continue
    return 0;
}

// Wait for YIELD response and extract string
static const char* supervisor_wait_yield(void) {
    static char buf[8192];
    static char response[4096];
    response[0] = '\0';

    if (!fgets(buf, sizeof(buf), stdin)) {
        return response;
    }

    // Extract response string
    char* resp_pos = strstr(buf, "\"response\"");
    if (resp_pos) {
        char* colon = strchr(resp_pos, ':');
        if (colon) {
            char* start = strchr(colon, '"');
            if (start) {
                start++;
                char* end = strchr(start, '"');
                if (end) {
                    int len = end - start;
                    if (len >= sizeof(response)) len = sizeof(response) - 1;
                    strncpy(response, start, len);
                    response[len] = '\0';
                }
            }
        }
    }
    return response;
}

// === Vector Operations (Semantic Computing) ===
// Vector format: [dims:int64][double][double]...
// Results scaled by 1_000_000 for integer precision
#include <math.h>

static int64_t vec_alloc(int64_t dims) {
    size_t size = 8 + dims * 8;
    char* data = calloc(1, size);
    *((int64_t*)data) = dims;
    int64_t ptr = heap_alloc(data, size);
    free(data);
    return ptr;
}

static int64_t vec_dims(int64_t ptr) {
    unsigned char* data = heap_get(ptr);
    if (!data) return 0;
    return *((int64_t*)data);
}

static double vec_get(int64_t ptr, int64_t idx) {
    unsigned char* data = heap_get(ptr);
    if (!data) return 0.0;
    return *((double*)(data + 8 + idx * 8));
}

static void vec_set(int64_t ptr, int64_t idx, double val) {
    unsigned char* data = heap_get(ptr);
    if (!data) return;
    *((double*)(data + 8 + idx * 8)) = val;
}

static int64_t vec_dot(int64_t v1, int64_t v2) {
    int64_t d1 = vec_dims(v1), d2 = vec_dims(v2);
    int64_t dims = d1 < d2 ? d1 : d2;
    double dot = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        dot += vec_get(v1, i) * vec_get(v2, i);
    }
    return (int64_t)(dot * 1000000.0);
}

static int64_t vec_sim(int64_t v1, int64_t v2) {
    int64_t d1 = vec_dims(v1), d2 = vec_dims(v2);
    int64_t dims = d1 < d2 ? d1 : d2;
    double dot = 0.0, mag1 = 0.0, mag2 = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double a = vec_get(v1, i), b = vec_get(v2, i);
        dot += a * b;
        mag1 += a * a;
        mag2 += b * b;
    }
    if (mag1 > 0 && mag2 > 0) {
        return (int64_t)((dot / (sqrt(mag1) * sqrt(mag2))) * 1000000.0);
    }
    return 0;
}

static int64_t vec_mag(int64_t ptr) {
    int64_t dims = vec_dims(ptr);
    double mag = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double v = vec_get(ptr, i);
        mag += v * v;
    }
    return (int64_t)(sqrt(mag) * 1000000.0);
}

static void vec_norm(int64_t ptr) {
    int64_t dims = vec_dims(ptr);
    double mag = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double v = vec_get(ptr, i);
        mag += v * v;
    }
    mag = sqrt(mag);
    if (mag > 0) {
        for (int64_t i = 0; i < dims; i++) {
            vec_set(ptr, i, vec_get(ptr, i) / mag);
        }
    }
}

"#);

    // Main function - the actual program
    code.push_str("// === Main Program ===\nint main() {\n");
    code.push_str("    heap_init();\n");
    code.push_str("    srand(time(NULL));\n\n");

    // Generate code for each instruction
    for (i, instr) in program.iter().enumerate() {
        code.push_str(&format!("L{}:\n", i));
        code.push_str(&generate_instruction(instr, i, tools));
    }

    code.push_str("\n    // Cleanup\n");
    code.push_str("    if (heap_buffer) free(heap_buffer);\n");
    code.push_str("    return 0;\n}\n");

    code
}

fn generate_instruction(instr: &Instruction, _line: usize, _tools: &HashMap<u16, (String, String)>) -> String {
    match instr {
        Instruction::NOP => "    // NOP\n".to_string(),

        Instruction::HALT => "    return 0;\n".to_string(),

        Instruction::PANIC(msg) => format!("    fprintf(stderr, \"PANIC: {}\\n\"); exit(1);\n", msg),

        Instruction::DUMP => r#"    printf("--- DUMP ---\n");
    for (int i = 0; i < 16; i++) printf("R%d=%ld ", i, (long)regs[i]);
    printf("\n");
"#.to_string(),

        Instruction::GAS(reg) => format!("    regs[{}] = 1000000; // GAS\n", reg),

        Instruction::ASSERT(reg) => format!(
            "    if (regs[{}] == 0) {{ fprintf(stderr, \"ASSERT FAILED\\n\"); exit(1); }}\n", reg),

        Instruction::SET { reg, val } => format!("    regs[{}] = {}LL;\n", reg, val),

        Instruction::SETS { reg, val } => {
            let escaped = val.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
            format!("    regs[{}] = heap_alloc_str(\"{}\");\n", reg, escaped)
        }

        Instruction::MOV { dest, src } => format!("    regs[{}] = regs[{}];\n", dest, src),

        Instruction::SWAP { r1, r2 } => format!(
            "    {{ int64_t t = regs[{}]; regs[{}] = regs[{}]; regs[{}] = t; }}\n", r1, r1, r2, r2),

        Instruction::ADD { dest, s1, s2 } => format!("    regs[{}] = regs[{}] + regs[{}];\n", dest, s1, s2),
        Instruction::SUB { dest, s1, s2 } => format!("    regs[{}] = regs[{}] - regs[{}];\n", dest, s1, s2),
        Instruction::MUL { dest, s1, s2 } => format!("    regs[{}] = regs[{}] * regs[{}];\n", dest, s1, s2),
        Instruction::DIV { dest, s1, s2 } => format!(
            "    if (regs[{}] != 0) regs[{}] = regs[{}] / regs[{}];\n", s2, dest, s1, s2),
        Instruction::MOD { dest, s1, s2 } => format!(
            "    if (regs[{}] != 0) regs[{}] = regs[{}] %% regs[{}];\n", s2, dest, s1, s2),

        Instruction::AND { dest, s1, s2 } => format!("    regs[{}] = regs[{}] & regs[{}];\n", dest, s1, s2),
        Instruction::OR { dest, s1, s2 } => format!("    regs[{}] = regs[{}] | regs[{}];\n", dest, s1, s2),
        Instruction::XOR { dest, s1, s2 } => format!("    regs[{}] = regs[{}] ^ regs[{}];\n", dest, s1, s2),
        Instruction::NOT { dest, src } => format!("    regs[{}] = ~regs[{}];\n", dest, src),

        Instruction::CMP { r1, r2 } => format!(
            "    flag_eq = (regs[{}] == regs[{}]); flag_gt = (regs[{}] > regs[{}]); flag_lt = (regs[{}] < regs[{}]);\n",
            r1, r2, r1, r2, r1, r2),

        Instruction::JMP { target } => format!("    goto L{};\n", target),
        Instruction::BEQ { target } => format!("    if (flag_eq) goto L{};\n", target),
        Instruction::BGT { target } => format!("    if (flag_gt) goto L{};\n", target),
        Instruction::BLT { target } => format!("    if (flag_lt) goto L{};\n", target),

        Instruction::NEW { dest, size } => format!(
            "    regs[{}] = heap_alloc(NULL, {});\n", dest, size),

        Instruction::FREE { ptr } => format!("    heap_free(regs[{}]);\n", ptr),

        Instruction::READ { dest, ptr, offset } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); regs[{}] = p ? p[{}] : 0; }}\n", ptr, dest, offset),

        Instruction::WRITE { ptr, offset, val } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); if (p) p[{}] = (char)regs[{}]; }}\n", ptr, offset, val),

        Instruction::TEXEC { tool, arg, dest } => format!(
            "    texec(0x{:04X}, {}, {});\n", tool, arg, dest),

        Instruction::ITOA { dest, src } => format!("    itoa_reg({}, {});\n", dest, src),

        Instruction::ATOI { dest, src } => format!("    atoi_reg({}, {});\n", dest, src),

        Instruction::READR { dest, ptr, off } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); regs[{}] = p ? p[regs[{}]] : 0; }}\n", ptr, dest, off),

        Instruction::WRITER { ptr, off, val } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); if (p) p[regs[{}]] = (char)regs[{}]; }}\n", ptr, off, val),

        Instruction::SCAT { dest, s1, s2 } => format!("    scat_reg({}, {}, {});\n", dest, s1, s2),

        Instruction::STORE64 { ptr, off, val } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); if (p) *((int64_t*)(p + regs[{}] * 8)) = regs[{}]; }}\n", ptr, off, val),

        Instruction::LOAD64 { dest, ptr, off } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); regs[{}] = p ? *((int64_t*)(p + regs[{}] * 8)) : 0; }}\n", ptr, dest, off),

        // Batch Memory Operations
        Instruction::MEMCPY { dst, doff, src, soff, len } => format!(
            "    {{ unsigned char* d = heap_get(regs[{}]); unsigned char* s = heap_get(regs[{}]); if (d && s) memcpy(d + regs[{}], s + regs[{}], regs[{}]); }}\n",
            dst, src, doff, soff, len),

        Instruction::HLEN { dest, ptr } => format!(
            "    regs[{}] = heap_len(regs[{}]);\n", dest, ptr),

        Instruction::SLICE { dest, ptr, off, len } => format!(
            "    {{ unsigned char* src = heap_get(regs[{}]); size_t o = regs[{}]; size_t l = regs[{}]; regs[{}] = src ? heap_alloc((const char*)(src + o), l) : 0; }}\n",
            ptr, off, len, dest),

        Instruction::MEMSET { ptr, off, len, val } => format!(
            "    {{ unsigned char* p = heap_get(regs[{}]); if (p) memset(p + regs[{}], (char)regs[{}], regs[{}]); }}\n",
            ptr, off, val, len),

        // REGEX instruction
        Instruction::REGEX { dest, pat, text } => format!(
            "    regs[{}] = regex_match(heap_str(regs[{}]), heap_str(regs[{}]));\n", dest, pat, text),

        // Vector Operations (Semantic Computing)
        Instruction::VNEW { dest, dims } => format!(
            "    regs[{}] = vec_alloc(regs[{}]);\n", dest, dims),

        Instruction::VSET { vec, idx, val } => format!(
            "    vec_set(regs[{}], regs[{}], *((double*)&regs[{}]));\n", vec, idx, val),

        Instruction::VGET { dest, vec, idx } => format!(
            "    {{ double v = vec_get(regs[{}], regs[{}]); regs[{}] = *((int64_t*)&v); }}\n", vec, idx, dest),

        Instruction::VDOT { dest, v1, v2 } => format!(
            "    regs[{}] = vec_dot(regs[{}], regs[{}]);\n", dest, v1, v2),

        Instruction::VSIM { dest, v1, v2 } => format!(
            "    regs[{}] = vec_sim(regs[{}], regs[{}]);\n", dest, v1, v2),

        Instruction::VMAG { dest, vec } => format!(
            "    regs[{}] = vec_mag(regs[{}]);\n", dest, vec),

        Instruction::VNORM { vec } => format!(
            "    vec_norm(regs[{}]);\n", vec),

        // Governance (with supervisor interaction)
        Instruction::LATCH { target, threshold } => format!(
            r#"    regs[240] = regs[{}]; regs[242] = regs[{}]; fprintf(stderr, "[GOVERNANCE] Latched target_vec=R240, threshold=%lld\n", (long long)regs[242]);
"#, target, threshold),

        Instruction::GUARD { state } => format!(r#"    {{
        int64_t sim = vec_sim(regs[240], regs[{state}]);
        regs[243] = sim;
        fprintf(stderr, "[GOVERNANCE] GUARD: similarity=%lld, threshold=%lld\n", (long long)sim, (long long)regs[242]);
        if (sim < regs[242]) {{
            fprintf(stderr, "[GOVERNANCE] DRIFT DETECTED! Triggering TRAP...\n");
            current_pc = __LINE__;
            supervisor_emit_drift(current_pc, sim, {state});
            int new_pc = 0;
            int action = supervisor_wait(&new_pc);
            if (action == 1) {{ fprintf(stderr, "[GOVERNANCE] Aborted by supervisor\n"); exit(2); }}
            if (action == 2) {{ /* jump handled by goto below */ }}
        }}
    }}
"#, state = state),

        Instruction::TRAP { code } => format!(r#"    {{
        current_pc = __LINE__;
        fprintf(stderr, "[GOVERNANCE] TRAP {code}: Awaiting supervisor...\n");
        supervisor_emit_trap("MANUAL", {code}, current_pc);
        int new_pc = 0;
        int action = supervisor_wait(&new_pc);
        if (action == 1) {{ exit({code}); }}
    }}
"#, code = code),

        Instruction::YIELD { query, dest } => format!(r#"    {{
        current_pc = __LINE__;
        const char* query_str = heap_str(regs[{query}]);
        supervisor_emit_yield(query_str, {query}, current_pc);
        const char* response = supervisor_wait_yield();
        regs[{dest}] = heap_alloc_str(response);
        fprintf(stderr, "[GOVERNANCE] YIELD response stored in R{dest}\n");
    }}
"#, query = query, dest = dest),
    }
}
