// L-0 AOT Compiler - Generates C code from L-0 bytecode
// Uses proxy call interface for TEXEC to support dynamic plugins
//
// 编译: cargo build --release --bin l0cc
// 用法: l0cc program.l0 -o program.c && gcc -O2 program.c -o program

mod lib;
use lib::*;
use std::env;
use std::fs;
use std::collections::HashMap;
use serde_json::Value;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("L-0 AOT Compiler");
        eprintln!("Usage: l0cc <program.l0|program.json> [-o output.c]");
        eprintln!("       l0cc --standalone <program> [-o output.c]  # Generate self-contained binary");
        std::process::exit(1);
    }

    let standalone = args.contains(&"--standalone".to_string());
    let input_path = args.iter().skip(1).find(|a| !a.starts_with("-") && *a != "--standalone")
        .expect("No input file specified");

    let output_path = args.iter().position(|a| a == "-o")
        .and_then(|i| args.get(i + 1))
        .map(|s| s.as_str())
        .unwrap_or("output.c");

    // Load program
    let program: Vec<Instruction> = if input_path.ends_with(".json") {
        let content = fs::read_to_string(input_path).expect("Failed to read JSON file");
        serde_json::from_str(&content).expect("Failed to parse L-0 JSON program")
    } else {
        let content = fs::read(input_path).expect("Failed to read binary file");
        bincode::deserialize(&content).expect("Failed to parse L-0 Binary Bytecode")
    };

    // Load tools.json for TEXEC mapping
    let tools = load_tools();

    // Generate C code
    let c_code = generate_c_code(&program, &tools, standalone);

    fs::write(output_path, &c_code).expect("Failed to write output file");
    eprintln!("Generated: {} ({} bytes)", output_path, c_code.len());
    eprintln!("Compile with: gcc -O2 {} -o program", output_path);
}

fn load_tools() -> HashMap<u16, (String, String)> {
    let mut tools = HashMap::new();
    let paths = ["tools.json", "env/tools.json"];

    for path in &paths {
        if let Ok(content) = fs::read_to_string(path) {
            if let Ok(json) = serde_json::from_str::<Value>(&content) {
                for section in ["plugins", "builtins"] {
                    if let Some(plugins) = json.get(section) {
                        if let Some(obj) = plugins.as_object() {
                            for (k, v) in obj {
                                let id = if k.starts_with("0x") {
                                    u16::from_str_radix(&k[2..], 16).unwrap_or(0)
                                } else {
                                    k.parse().unwrap_or(0)
                                };
                                let name = v["name"].as_str().unwrap_or("UNKNOWN").to_string();
                                let kind = v["type"].as_str().unwrap_or("builtin").to_string();
                                tools.insert(id, (name, kind));
                            }
                        }
                    }
                }
            }
            break;
        }
    }
    tools
}

fn generate_c_code(program: &[Instruction], tools: &HashMap<u16, (String, String)>, standalone: bool) -> String {
    let mut code = String::new();

    // Header
    code.push_str(r#"/*
 * L-0 AOT Compiled Program
 * Generated by l0cc (L-0 Ahead-of-Time Compiler)
 *
 * Compile: gcc -O2 -o program program.c
 * Run: ./program
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <time.h>

// === VM State ===
static int64_t regs[256];
static char* heap[4096];
static int heap_count = 0;
static int flag_eq = 0, flag_gt = 0, flag_lt = 0;

// === Heap Management ===
static int heap_alloc(const char* data, int len) {
    if (heap_count >= 4096) return -1;
    heap[heap_count] = malloc(len + 1);
    if (data) memcpy(heap[heap_count], data, len);
    heap[heap_count][len] = '\0';
    return heap_count++;
}

static int heap_alloc_str(const char* str) {
    return heap_alloc(str, strlen(str));
}

static char* heap_get(int idx) {
    if (idx < 0 || idx >= heap_count || !heap[idx]) return "";
    return heap[idx];
}

static void heap_free(int idx) {
    if (idx >= 0 && idx < heap_count && heap[idx]) {
        free(heap[idx]);
        heap[idx] = NULL;
    }
}

"#);

    // TEXEC proxy - key feature for dynamic plugin support
    code.push_str(r#"// === TEXEC Proxy (supports dynamic plugins via tools.json) ===
static char* texec_builtin(int tool_id, const char* arg) {
    static char buf[4096];
    buf[0] = '\0';

    switch (tool_id) {
        case 0x5000: // PRINT
            printf("%s\n", arg);
            break;
        case 0x5001: // PRINTN
            printf("%s", arg);
            fflush(stdout);
            break;
        case 0x5002: // INPUT
            if (fgets(buf, sizeof(buf), stdin)) {
                buf[strcspn(buf, "\n")] = '\0';
            }
            break;
        case 0x5003: // RAND
            snprintf(buf, sizeof(buf), "%ld", (long)(rand() % (atol(arg) ?: 100)));
            break;
        case 0x5004: // STRLEN
            snprintf(buf, sizeof(buf), "%lu", (unsigned long)strlen(arg));
            break;
        case 0x5005: // ABS
            snprintf(buf, sizeof(buf), "%ld", labs(atol(arg)));
            break;
        case 0x5006: // MIN
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2)
                    snprintf(buf, sizeof(buf), "%ld", a < b ? a : b);
            }
            break;
        case 0x5007: // MAX
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2)
                    snprintf(buf, sizeof(buf), "%ld", a > b ? a : b);
            }
            break;
        case 0x5008: // TIME
            snprintf(buf, sizeof(buf), "%ld", (long)time(NULL));
            break;
        case 0x5009: // CONCAT
            {
                const char* comma = strchr(arg, ',');
                if (comma) {
                    int len1 = comma - arg;
                    snprintf(buf, sizeof(buf), "%.*s%s", len1, arg, comma + 1);
                }
            }
            break;
        case 0x500C: // UPPER
            for (int i = 0; arg[i] && i < sizeof(buf)-1; i++)
                buf[i] = (arg[i] >= 'a' && arg[i] <= 'z') ? arg[i] - 32 : arg[i];
            break;
        case 0x500D: // LOWER
            for (int i = 0; arg[i] && i < sizeof(buf)-1; i++)
                buf[i] = (arg[i] >= 'A' && arg[i] <= 'Z') ? arg[i] + 32 : arg[i];
            break;
        case 0x500E: // TRIM
            {
                const char* start = arg;
                while (*start == ' ' || *start == '\t') start++;
                const char* end = arg + strlen(arg) - 1;
                while (end > start && (*end == ' ' || *end == '\t')) end--;
                int len = end - start + 1;
                strncpy(buf, start, len);
                buf[len] = '\0';
            }
            break;
        case 0x1004: // POW
            {
                long a, b;
                if (sscanf(arg, "%ld,%ld", &a, &b) == 2) {
                    long result = 1;
                    for (int i = 0; i < b; i++) result *= a;
                    snprintf(buf, sizeof(buf), "%ld", result);
                }
            }
            break;
        default:
            snprintf(buf, sizeof(buf), "[Tool 0x%04X not implemented]", tool_id);
    }
    return buf;
}

// Plugin proxy - calls external plugins via pipe
static char* texec_plugin(int tool_id, const char* arg) {
    static char buf[4096];
    buf[0] = '\0';

    // For standalone mode, plugins are not supported
    // In full mode, this would spawn the plugin process
    snprintf(buf, sizeof(buf), "[Plugin 0x%04X requires runtime]", tool_id);
    return buf;
}

static int texec(int tool_id, int arg_reg, int dest_reg) {
    const char* arg = heap_get(regs[arg_reg]);
    char* result;

    // Check if builtin (0x5xxx, 0x1xxx) or plugin (others)
    if ((tool_id & 0xF000) == 0x5000 || (tool_id & 0xF000) == 0x1000) {
        result = texec_builtin(tool_id, arg);
    } else {
        result = texec_plugin(tool_id, arg);
    }

    regs[dest_reg] = heap_alloc_str(result);
    return 0;
}

"#);

    // Helper functions
    code.push_str(r#"// === Helper Functions ===
static void itoa_reg(int dest, int src) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%ld", (long)regs[src]);
    regs[dest] = heap_alloc_str(buf);
}

static void atoi_reg(int dest, int src) {
    regs[dest] = atol(heap_get(regs[src]));
}

static void scat_reg(int dest, int s1, int s2) {
    const char* str1 = heap_get(regs[s1]);
    const char* str2 = heap_get(regs[s2]);
    int len = strlen(str1) + strlen(str2);
    char* buf = malloc(len + 1);
    strcpy(buf, str1);
    strcat(buf, str2);
    regs[dest] = heap_count;
    heap[heap_count++] = buf;
}

// Simple regex match using POSIX regex (compile with -lregex on some systems)
#include <regex.h>
static int regex_match(const char* pattern, const char* text) {
    regex_t re;
    if (regcomp(&re, pattern, REG_EXTENDED | REG_NOSUB) != 0) return 0;
    int result = (regexec(&re, text, 0, NULL, 0) == 0) ? 1 : 0;
    regfree(&re);
    return result;
}

// === Vector Operations (Semantic Computing) ===
// Vector format: [dims:int64][double][double]...
// Results scaled by 1_000_000 for integer precision
#include <math.h>

static int vec_alloc(int64_t dims) {
    int size = 8 + dims * 8;
    char* data = calloc(1, size);
    *((int64_t*)data) = dims;
    return heap_count;
    heap[heap_count++] = data;
}

static int64_t vec_dims(int vec_idx) {
    if (vec_idx < 0 || vec_idx >= heap_count || !heap[vec_idx]) return 0;
    return *((int64_t*)heap[vec_idx]);
}

static double vec_get(int vec_idx, int64_t idx) {
    if (vec_idx < 0 || vec_idx >= heap_count || !heap[vec_idx]) return 0.0;
    return *((double*)(heap[vec_idx] + 8 + idx * 8));
}

static void vec_set(int vec_idx, int64_t idx, double val) {
    if (vec_idx < 0 || vec_idx >= heap_count || !heap[vec_idx]) return;
    *((double*)(heap[vec_idx] + 8 + idx * 8)) = val;
}

static int64_t vec_dot(int v1, int v2) {
    int64_t d1 = vec_dims(v1), d2 = vec_dims(v2);
    int64_t dims = d1 < d2 ? d1 : d2;
    double dot = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        dot += vec_get(v1, i) * vec_get(v2, i);
    }
    return (int64_t)(dot * 1000000.0);
}

static int64_t vec_sim(int v1, int v2) {
    int64_t d1 = vec_dims(v1), d2 = vec_dims(v2);
    int64_t dims = d1 < d2 ? d1 : d2;
    double dot = 0.0, mag1 = 0.0, mag2 = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double a = vec_get(v1, i), b = vec_get(v2, i);
        dot += a * b;
        mag1 += a * a;
        mag2 += b * b;
    }
    if (mag1 > 0 && mag2 > 0) {
        return (int64_t)((dot / (sqrt(mag1) * sqrt(mag2))) * 1000000.0);
    }
    return 0;
}

static int64_t vec_mag(int vec_idx) {
    int64_t dims = vec_dims(vec_idx);
    double mag = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double v = vec_get(vec_idx, i);
        mag += v * v;
    }
    return (int64_t)(sqrt(mag) * 1000000.0);
}

static void vec_norm(int vec_idx) {
    int64_t dims = vec_dims(vec_idx);
    double mag = 0.0;
    for (int64_t i = 0; i < dims; i++) {
        double v = vec_get(vec_idx, i);
        mag += v * v;
    }
    mag = sqrt(mag);
    if (mag > 0) {
        for (int64_t i = 0; i < dims; i++) {
            vec_set(vec_idx, i, vec_get(vec_idx, i) / mag);
        }
    }
}

"#);

    // Main function - the actual program
    code.push_str("// === Main Program ===\nint main() {\n");
    code.push_str("    srand(time(NULL));\n\n");

    // Generate code for each instruction
    for (i, instr) in program.iter().enumerate() {
        code.push_str(&format!("L{}:\n", i));
        code.push_str(&generate_instruction(instr, i, tools));
    }

    code.push_str("\n    // Cleanup\n");
    code.push_str("    for (int i = 0; i < heap_count; i++) if (heap[i]) free(heap[i]);\n");
    code.push_str("    return 0;\n}\n");

    code
}

fn generate_instruction(instr: &Instruction, _line: usize, _tools: &HashMap<u16, (String, String)>) -> String {
    match instr {
        Instruction::NOP => "    // NOP\n".to_string(),

        Instruction::HALT => "    return 0;\n".to_string(),

        Instruction::PANIC(msg) => format!("    fprintf(stderr, \"PANIC: {}\\n\"); exit(1);\n", msg),

        Instruction::DUMP => r#"    printf("--- DUMP ---\n");
    for (int i = 0; i < 16; i++) printf("R%d=%ld ", i, (long)regs[i]);
    printf("\n");
"#.to_string(),

        Instruction::GAS(reg) => format!("    regs[{}] = 1000000; // GAS\n", reg),

        Instruction::ASSERT(reg) => format!(
            "    if (regs[{}] == 0) {{ fprintf(stderr, \"ASSERT FAILED\\n\"); exit(1); }}\n", reg),

        Instruction::SET { reg, val } => format!("    regs[{}] = {}LL;\n", reg, val),

        Instruction::SETS { reg, val } => {
            let escaped = val.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n");
            format!("    regs[{}] = heap_alloc_str(\"{}\");\n", reg, escaped)
        }

        Instruction::MOV { dest, src } => format!("    regs[{}] = regs[{}];\n", dest, src),

        Instruction::SWAP { r1, r2 } => format!(
            "    {{ int64_t t = regs[{}]; regs[{}] = regs[{}]; regs[{}] = t; }}\n", r1, r1, r2, r2),

        Instruction::ADD { dest, s1, s2 } => format!("    regs[{}] = regs[{}] + regs[{}];\n", dest, s1, s2),
        Instruction::SUB { dest, s1, s2 } => format!("    regs[{}] = regs[{}] - regs[{}];\n", dest, s1, s2),
        Instruction::MUL { dest, s1, s2 } => format!("    regs[{}] = regs[{}] * regs[{}];\n", dest, s1, s2),
        Instruction::DIV { dest, s1, s2 } => format!(
            "    if (regs[{}] != 0) regs[{}] = regs[{}] / regs[{}];\n", s2, dest, s1, s2),
        Instruction::MOD { dest, s1, s2 } => format!(
            "    if (regs[{}] != 0) regs[{}] = regs[{}] %% regs[{}];\n", s2, dest, s1, s2),

        Instruction::AND { dest, s1, s2 } => format!("    regs[{}] = regs[{}] & regs[{}];\n", dest, s1, s2),
        Instruction::OR { dest, s1, s2 } => format!("    regs[{}] = regs[{}] | regs[{}];\n", dest, s1, s2),
        Instruction::XOR { dest, s1, s2 } => format!("    regs[{}] = regs[{}] ^ regs[{}];\n", dest, s1, s2),
        Instruction::NOT { dest, src } => format!("    regs[{}] = ~regs[{}];\n", dest, src),

        Instruction::CMP { r1, r2 } => format!(
            "    flag_eq = (regs[{}] == regs[{}]); flag_gt = (regs[{}] > regs[{}]); flag_lt = (regs[{}] < regs[{}]);\n",
            r1, r2, r1, r2, r1, r2),

        Instruction::JMP { target } => format!("    goto L{};\n", target),
        Instruction::BEQ { target } => format!("    if (flag_eq) goto L{};\n", target),
        Instruction::BGT { target } => format!("    if (flag_gt) goto L{};\n", target),
        Instruction::BLT { target } => format!("    if (flag_lt) goto L{};\n", target),

        Instruction::NEW { dest, size } => format!(
            "    regs[{}] = heap_alloc(NULL, {});\n", dest, size),

        Instruction::FREE { ptr } => format!("    heap_free(regs[{}]);\n", ptr),

        Instruction::READ { dest, ptr, offset } => format!(
            "    regs[{}] = (unsigned char)heap_get(regs[{}])[{}];\n", dest, ptr, offset),

        Instruction::WRITE { ptr, offset, val } => format!(
            "    heap_get(regs[{}])[{}] = (char)regs[{}];\n", ptr, offset, val),

        Instruction::TEXEC { tool, arg, dest } => format!(
            "    texec(0x{:04X}, {}, {});\n", tool, arg, dest),

        Instruction::ITOA { dest, src } => format!("    itoa_reg({}, {});\n", dest, src),

        Instruction::ATOI { dest, src } => format!("    atoi_reg({}, {});\n", dest, src),

        Instruction::READR { dest, ptr, off } => format!(
            "    regs[{}] = (unsigned char)heap_get(regs[{}])[regs[{}]];\n", dest, ptr, off),

        Instruction::WRITER { ptr, off, val } => format!(
            "    heap_get(regs[{}])[regs[{}]] = (char)regs[{}];\n", ptr, off, val),

        Instruction::SCAT { dest, s1, s2 } => format!("    scat_reg({}, {}, {});\n", dest, s1, s2),

        Instruction::STORE64 { ptr, off, val } => format!(
            "    *((int64_t*)(heap_get(regs[{}]) + regs[{}] * 8)) = regs[{}];\n", ptr, off, val),

        Instruction::LOAD64 { dest, ptr, off } => format!(
            "    regs[{}] = *((int64_t*)(heap_get(regs[{}]) + regs[{}] * 8));\n", dest, ptr, off),

        // Batch Memory Operations
        Instruction::MEMCPY { dst, doff, src, soff, len } => format!(
            "    memcpy(heap_get(regs[{}]) + regs[{}], heap_get(regs[{}]) + regs[{}], regs[{}]);\n",
            dst, doff, src, soff, len),

        Instruction::HLEN { dest, ptr } => format!(
            "    regs[{}] = strlen(heap_get(regs[{}]));\n", dest, ptr),

        Instruction::SLICE { dest, ptr, off, len } => format!(
            "    {{ char* src = heap_get(regs[{}]); int o = regs[{}]; int l = regs[{}]; regs[{}] = heap_alloc(src + o, l); }}\n",
            ptr, off, len, dest),

        Instruction::MEMSET { ptr, off, len, val } => format!(
            "    memset(heap_get(regs[{}]) + regs[{}], (char)regs[{}], regs[{}]);\n",
            ptr, off, val, len),

        // REGEX instruction
        Instruction::REGEX { dest, pat, text } => format!(
            "    regs[{}] = regex_match(heap_get(regs[{}]), heap_get(regs[{}]));\n", dest, pat, text),

        // Vector Operations (Semantic Computing)
        Instruction::VNEW { dest, dims } => format!(
            "    {{ int64_t d = regs[{}]; int sz = 8 + d * 8; char* v = calloc(1, sz); *((int64_t*)v) = d; regs[{}] = heap_count; heap[heap_count++] = v; }}\n",
            dims, dest),

        Instruction::VSET { vec, idx, val } => format!(
            "    vec_set(regs[{}], regs[{}], *((double*)&regs[{}]));\n", vec, idx, val),

        Instruction::VGET { dest, vec, idx } => format!(
            "    {{ double v = vec_get(regs[{}], regs[{}]); regs[{}] = *((int64_t*)&v); }}\n", vec, idx, dest),

        Instruction::VDOT { dest, v1, v2 } => format!(
            "    regs[{}] = vec_dot(regs[{}], regs[{}]);\n", dest, v1, v2),

        Instruction::VSIM { dest, v1, v2 } => format!(
            "    regs[{}] = vec_sim(regs[{}], regs[{}]);\n", dest, v1, v2),

        Instruction::VMAG { dest, vec } => format!(
            "    regs[{}] = vec_mag(regs[{}]);\n", dest, vec),

        Instruction::VNORM { vec } => format!(
            "    vec_norm(regs[{}]);\n", vec),

        // Governance (simplified for AOT - no supervisor interaction)
        Instruction::LATCH { target, threshold } => format!(
            "    regs[240] = regs[{}]; regs[242] = regs[{}]; /* LATCH target, threshold */\n",
            target, threshold),

        Instruction::GUARD { state } => format!(
            "    {{ int64_t sim = vec_sim(regs[240], regs[{}]); regs[243] = sim; if (sim < regs[242]) {{ fprintf(stderr, \"DRIFT: sim=%%ld < threshold=%%ld\\n\", sim, regs[242]); exit(2); }} }}\n",
            state),

        Instruction::TRAP { code } => format!(
            "    fprintf(stderr, \"TRAP code={}\\n\"); exit({});\n", code, code),

        Instruction::YIELD { query, dest } => format!(
            "    regs[{}] = regs[{}]; /* YIELD (no-op in AOT) */\n", dest, query),
    }
}
